@base_url = http://localhost:5000
@course_id = 68d6f224b63b94d581c583d5
@lesson_id = 68d7066f44ad3fe970376bcf

# GEt all courses
GET {{base_url}}/courses/


###

# Get a single course
GET {{base_url}}/courses/{{course_id}}

###

# Delete a single course
DELETE  {{base_url}}/courses/{{course_id}}

###

# Create a course
POST {{base_url}}/courses/create
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="thumbnail"; filename="thumbnail.jpg"
Content-Type: image/jpeg

< ./test.jpg 

--boundary
Content-Disposition: form-data; name="title"

lorem ipsum dolor
--boundary
Content-Disposition: form-data; name="description"

lorem ipsum dolor
--boundary
Content-Disposition: form-data; name="price"

5000
--boundary--


###

# Edit a course 
POST {{base_url}}/courses/{{course_id}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="thumbnail"; filename="thumbnail.jpg"
Content-Type: image/jpeg

< ./test.jpg

--boundary
Content-Disposition: form-data; name="title"

a very good course 
--boundary--

# Content-Disposition: form-data; name="thumbnail"; filename="thumbnail.jpg"
# Content-Type: image/jpeg

# < ./test.jpg 

# --boundary


###
POST {{base_url}}/courses/{{course_id}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

lorem ipsum 
--boundary
Content-Disposition: form-data; name="description"

lorem ipsum dolor
--boundary
Content-Disposition: form-data; name="price"

78000
--boundary--

###

# Add a new lesson
POST {{base_url}}/courses/{{course_id}}/lessons
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

great lesson
--boundary
Content-Disposition: form-data; name="text"

lorem ipsum dolor sit amet kwmxlmk  kcllnpkewnoepo jkenofcm mdpo3k kjmcjnd nnm jjndoi
--boundary
Content-Disposition: form-data; name="lessonFiles"; filename="lessonFile1.pdf"
Content-Type: application/pdf

< ./test.pdf
--boundary
Content-Disposition: form-data; name="lessonFiles"; filename="lessonFile2.pdf"
Content-Type: application/pdf

< ./test.pdf
--boundary
Content-Disposition: form-data; name="lessonVideo"; filename="lessonVideo.mp4"
Content-Type: video/mp4

< ./test.mp4
--boundary--

###

# Get a single lesson

GET {{base_url}}/courses/{{course_id}}/lessons/{{lesson_id}}

### 

# Delete a lesson
DELETE  {{base_url}}/courses/{{course_id}}/lessons/{{lesson_id}}
