# @base_url = https://fischerbon.onrender.com/enrollments
@base_url = http://localhost:5000/enrollments
@course_id = 68e381faa47a59914213fc7c
@lesson_id = 68d7066f44ad3fe970376bcf
@reference = hd8jq6t77n

@enrollmentId = 68e39ce6ce28cba635db7183


POST  {{base_url}}/new/{{course_id}}
Content-Type: application/json

###
GET http://localhost:5000/enrollments/verify/{{course_id}}?trxref=r8yfshdflx&reference={{reference}}
###

GET {{base_url}}/
###
GET {{base_url}}/{{enrollmentId}}

