@base_url = http://localhost:5000/enrollments
@course_id = 68bf0923de9feb5594dcc06e
@lesson_id = 68d7066f44ad3fe970376bcf



POST  {{base_url}}/new/{{course_id}}
Content-Type: application/json

###
GET http://localhost:5000/enrollments/verify/68bf0923de9feb5594dcc06e?trxref=3buj387750&reference=3buj387750